name: WorldOfGames CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      DOCKER_IMAGE: world-of-games
      SCORES_FILE: scores.db

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t $DOCKER_IMAGE .

    - name: Run Docker container
      run: |
        docker run -d --name test_container \
          -p 8777:8777 \
          -v $GITHUB_WORKSPACE/$SCORES_FILE:/app/scores.db \
          $DOCKER_IMAGE

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install python3
        sudo apt-get install pip3
        pip3 install -r requirements.txt

    - name: Run end-to-end tests
      run: |
        python3 tests/e2e.py
      continue-on-error: false

    - name: Stop and remove Docker container
      if: always()
      run: |
        docker stop test_container
        docker rm test_container

    - name: Push Docker image to DockerHub
      run: |
        docker tag $DOCKER_IMAGE ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/$DOCKER_IMAGE:latest
